# Generated by Django 3.1.2 on 2020-10-24 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Slug', models.CharField(max_length=120, unique=True)),
                ('Image', models.ImageField(upload_to='photo')),
                ('descraption', models.TextField()),
                ('Writer_Name', models.CharField(max_length=50, verbose_name='writer name :')),
                ('Published', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='P', max_length=1)),
            ],
        ),
    ]
