# Generated by Django 3.1.2 on 2020-10-24 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Slug', models.CharField(max_length=50, unique=True)),
                ('Position', models.IntegerField(unique=True)),
                ('Published', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'ordering': ['Position'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Article'},
        ),
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(to='Blog.Category'),
        ),
    ]
