# Generated by Django 3.1.2 on 2020-10-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20201024_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=1),
        ),
    ]
