# Generated by Django 3.1.2 on 2020-10-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20201024_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Status',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='To Be Published ?'),
        ),
    ]
