# Generated by Django 3.1.2 on 2020-10-25 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20201024_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-Published'], 'verbose_name': 'Article', 'verbose_name_plural': 'Article'},
        ),
        migrations.AlterField(
            model_name='article',
            name='Published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
