# Generated by Django 3.1.2 on 2020-10-25 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20201025_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(related_name='posts', to='Blog.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
